# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Apache-Imager-Resize
version:      0.10
version_from: lib/Apache/Imager/Resize.pm
installdirs:  site
requires:
    Apache:                        1
    File::Basename:                0
    Imager:                        0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.30
